# must be created before deployment
apiVersion: v1
kind: Secret
metadata:
    name: mongodb-secret
    # most basic key value secret type
type: Opaque
data:
# values here are not plain text must be base64 encoded
    # username = username
    mongo-root-username: dXNlcm5hbWU=
    # password = password
    # echo -n 'password' | base64 ---> to get to base64 
    mongo-root-password: cGFzc3dvcmQ=
