---
# this is techinically just a play not a playbook because there is 
# only one play taking place for webservers we could add another play
# for databases and then we would have a playbook

# a playbook describes
# how and in which order
# at what time and where (on which machines)
# what(the modules) should be executed (orchstrates module execution)

- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
  - name: write the apache config file
    template: src=/srv/httpd.j2 dest=/etc/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  handlers:
    - name: restart apache
      service: name=httpd state=restarted